development:
  cloud_name: dhtj2ifko
  api_key: '417283593312236'
  api_secret: Wkw3gnpD2egDnhZaeAxvO2ILYJk
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dhtj2ifko
  api_key: '417283593312236'
  api_secret: Wkw3gnpD2egDnhZaeAxvO2ILYJk
  enhance_image_tag: true
  static_image_support: true
staging:
  cloud_name: dhtj2ifko
  api_key: '417283593312236'
  api_secret: Wkw3gnpD2egDnhZaeAxvO2ILYJk
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dhtj2ifko
  api_key: '417283593312236'
  api_secret: Wkw3gnpD2egDnhZaeAxvO2ILYJk
  enhance_image_tag: true
  static_image_support: false
