default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: judoda09
  # socket: localhost
  host: 127.0.0.1

development:
  <<: *default
  database: TT_development

test:
  <<: *default
  database: TT_test

production:
  <<: *default
  database: TT_production
  username: GP
  password: <%= ENV['GP_DATABASE_PASSWORD'] %>

staging:
  <<: *default
  database: TT_staging
