default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: judoda09
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: GP_development

test:
  <<: *default
  database: GP_test

production:
  <<: *default
  database: GP_production
  username: GP
  password: <%= ENV['GP_DATABASE_PASSWORD'] %>

staging:
  <<: *default
  database: GP_staging
  password: judoda09
